INSERT INTO category (long_name, total) VALUES ('IT, комп''ютери, інтернет', '0');
INSERT INTO category (long_name, total) VALUES ('Адмiнiстрацiя, керівництво середньої ланки', '0');
INSERT INTO category (long_name, total) VALUES ('Будівництво, архітектура', '0');
INSERT INTO category (long_name, total) VALUES ('Бухгалтерія, аудит', '0');
INSERT INTO category (long_name, total) VALUES ('Готельно-ресторанний бізнес, туризм', '0');
INSERT INTO category (long_name, total) VALUES ('Дизайн, творчість', '0');
INSERT INTO category (long_name, total) VALUES ('ЗМІ, видавництво, поліграфія', '0');
INSERT INTO category (long_name, total) VALUES ('Краса, фітнес, спорт', '0');
INSERT INTO category (long_name, total) VALUES ('Культура, музика, шоу-бізнес', '0');
INSERT INTO category (long_name, total) VALUES ('Логістика, склад, ЗЕД', '0');
INSERT INTO category (long_name, total) VALUES ('Маркетинг, реклама, PR', '0');
INSERT INTO category (long_name, total) VALUES ('Медицина, фармацевтика', '0');
INSERT INTO category (long_name, total) VALUES ('Нерухомість', '0');
INSERT INTO category (long_name, total) VALUES ('Освіта, наука', '0');
INSERT INTO category (long_name, total) VALUES ('Охорона, безпека', '0');
INSERT INTO category (long_name, total) VALUES ('Продаж, закупівля', '0');
INSERT INTO category (long_name, total) VALUES ('Робочі спеціальності, виробництво', '0');
INSERT INTO category (long_name, total) VALUES ('Роздрібна торгівля', '0');
INSERT INTO category (long_name, total) VALUES ('Секретаріат, діловодство, АГВ', '0');
INSERT INTO category (long_name, total) VALUES ('Сільське господарство, агробізнес', '0');
INSERT INTO category (long_name, total) VALUES ('Страхування', '0');
INSERT INTO category (long_name, total) VALUES ('Сфера обслуговування', '0');
INSERT INTO category (long_name, total) VALUES ('Телекомунікації та зв''язок', '0');
INSERT INTO category (long_name, total) VALUES ('Топменеджмент, керівництво вищої ланки', '0');
INSERT INTO category (long_name, total) VALUES ('Транспорт, автобізнес', '0');
INSERT INTO category (long_name, total) VALUES ('Управління персоналом, HR', '0');
INSERT INTO category (long_name, total) VALUES ('Фінанси, банк', '0');
INSERT INTO category (long_name, total) VALUES ('Юриспруденція', '0');